### ISSUE TITLE
Interest summaries not showing in generated docx

### ISSUE THREAD

**Issue by jaguaar** [DominionExperts/de-resume#8]
Given I add interests with summaries to the JSON:
`{
			"name": "Skiing",
			"summary": "Avid skieer who refuses to miss any or all opportunities to be in the snow. I could talk about skiing all day if someone gets me going."
		},
{
			"name": "Reading",
			"summary": "My e-reader is never far away."
		},
		{
			"name": "Hiking",
			"summary": "Love to visit new forests & locations to hike in."
		}`

I expect them to show up in the CV.
Currently only the "name" shows up in the docx

**Comment by t-v** [comment]
Please review:
#10
