### ISSUE TITLE
First language not indented with a tab character

### ISSUE THREAD

**Issue by jaguaar** [DominionExperts/de-resume#9]
Given I add 3 languages, each with a level
`"languages": [
		{
			"language": "Dutch",
			"level": "Native"
		},
		{
			"language": "English",
			"level": "Good"
		},
		{
			"language": "French",
			"level": "Moderate"
		}
	],`

I expect all of them to be indented with a space after the language,
but right now the first of the 3 isn't.

[https://files.slack.com/files-pri/T0SQ36RA4-FHYPX68JD/image.png](See screenshot)

**Comment by t-v** [comment]
Please review:
https://github.com/DominionExperts/de-resume/pull/10

Was an easy fix
